const profile=window.PROFILE;
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bullets=items=>`<ul>${items.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul>`;
document.querySelector('#resume-content').innerHTML=`
 <div class="resume-grid"><div><h3 class="resume-headline">${profile.resume.headline}</h3><p class="profile-summary">${profile.summary}</p><a class="text-link" href="https://github.com/jbsim999" target="_blank" rel="noopener noreferrer">GitHub · jbsim999</a></div><div class="skills">${profile.skills.map(([name,value])=>`<div class="skill-row"><b>${name}</b><span>${value}</span></div>`).join('')}</div></div>
 <div class="resume-experience">${profile.resume.experience.map(c=>`<article class="resume-job"><div><p class="eyebrow">${c.period}</p><h3>${c.company}</h3><p class="role">${c.role}</p></div><div>${bullets(c.items)}${c.note?`<p class="resume-note">${c.note}</p>`:''}</div></article>`).join('')}</div>
 <div class="resume-background"><div><h3>이전 경력 · 업무 개선의 시작</h3><h4>${profile.resume.previous.company}</h4><p class="period">${profile.resume.previous.period}</p><p>${profile.resume.previous.description}</p><p class="resume-note">백엔드 개발 경력과 구분한 이전 직무 경험입니다.</p></div><div><h3>학력과 교육</h3>${profile.resume.education.map(e=>`<article class="education"><h4>${e.title}</h4><p class="period">${e.period}</p><p>${e.description}</p></article>`).join('')}</div></div>
 <div class="strengths">${profile.resume.strengths.map((s,i)=>`<article><span>0${i+1}</span><h4>${s.title}</h4><p>${s.description}</p></article>`).join('')}</div>`;
function codeExample(code,related){if(!code)return '';return `<details class="code-example"><summary>구현 코드 · ${escapeHtml(code.title)}</summary><p class="code-context">${escapeHtml(code.context)}</p><div class="code-comparison ${code.blocks.length===1?'single':''}">${code.blocks.map(block=>`<div><div class="code-label"><b>${escapeHtml(block.label)}</b><span>${escapeHtml(code.language)}</span></div><pre tabindex="0" aria-label="${escapeHtml(block.label)}"><code>${escapeHtml(block.source)}</code></pre></div>`).join('')}</div>${bullets(code.points)}<p class="code-note">${escapeHtml(code.note)}</p>${related?`<section class="related-work"><h4>${escapeHtml(related.title)}</h4><p>${escapeHtml(related.body)}</p></section>`:''}</details>`;}
function comparison(headers,rows){return `<div class="table-wrap"><table class="decision-table"><thead><tr>${headers.map(x=>`<th scope="col">${escapeHtml(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((cell,i)=>i===0?`<th scope="row">${escapeHtml(cell)}</th>`:`<td>${escapeHtml(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function screenExamples(p){if(!p.screens)return '';return `<details class="screen-details" open><summary>화면과 기능의 변화</summary><p class="screen-disclaimer">${escapeHtml(p.screens.caption)}</p><div class="screen-grid">${p.screens.items.map(s=>`<figure><a class="screen-link" href="${s.src}" target="_blank" rel="noopener noreferrer" aria-label="${escapeHtml(s.title)} 크게 보기"><img src="${s.src}" alt="${escapeHtml(s.title)}. 가상 데이터로 재구성한 설명용 화면." loading="lazy"></a><figcaption><b>${escapeHtml(s.title)}</b>${escapeHtml(s.description)}</figcaption></figure>`).join('')}</div>${comparison(['구분','개선 전','개선 후'],p.changes)}</details>`;}
document.querySelector('#project-content').innerHTML=profile.projects.map((p,i)=>`<article class="project-card" id="case-${i+1}"><div class="project-index">0${i+1}</div><div class="project-body"><div class="project-head"><div><p>${p.period}</p><h3>${p.title}</h3></div><div class="result">${p.result}</div></div><p class="project-description">${p.description}</p><p class="project-role">담당 범위 · ${p.role}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><ol class="project-flow" aria-label="구현 흐름">${p.flow.map(step=>`<li>${escapeHtml(step)}</li>`).join('')}</ol><details class="case-details"><summary>문제 해결 과정과 설계 판단</summary><div class="case-grid"><div><h4>문제</h4><p>${p.problem}</p></div><div><h4>접근과 실행</h4><p>${p.action}</p></div><div><h4>결과</h4><p>${p.outcome}</p></div></div><h4 class="case-section-title">구현에서 중요했던 판단</h4>${comparison(['쟁점','구현한 선택','의미와 고려사항'],p.decisions)}</details>${codeExample(p.code,p.related?.batch?null:p.related)}${p.related?.batch?window.renderBatchWork(p.related):''}${screenExamples(p)}</div></article>`).join('');
document.querySelector('#career-content').innerHTML=profile.career.map(c=>`<article class="career-item"><div><h3>${c.company}</h3><p class="period">${c.role}<br>${c.period}</p></div><div>${c.groups.map(([title,items])=>`<h4>${title}</h4>${bullets(items)}`).join('')}</div></article>`).join('')+`<p class="career-note">문의 감소율은 2024년 상반기와 2026년 상반기의 서비스 전체 문의 건수를 비교한 수치입니다.</p>`;
